import type { LearningPath } from "@/types";

export const learningPaths: LearningPath[] = [
  {
    id: "web",
    title: "Web Development",
    description: "From your first line of HTML to a full-stack project you can show off.",
    stages: [
      {
        title: "Programming Fundamentals",
        description: "Learn how to think like a programmer before diving into the browser.",
        skills: ["Variables & control flow", "Functions", "Basic debugging"],
        resources: [{ label: "freeCodeCamp: JavaScript Basics", url: "https://www.freecodecamp.org/learn" }],
        practiceProjectIdeas: ["A number-guessing game in the browser console"],
      },
      {
        title: "HTML and CSS",
        description: "Structure and style your first real web pages.",
        skills: ["Semantic HTML", "CSS layout (flexbox/grid)", "Responsive design"],
        resources: [{ label: "MDN: Learn HTML and CSS", url: "https://developer.mozilla.org/en-US/docs/Learn" }],
        practiceProjectIdeas: ["A personal landing page"],
      },
      {
        title: "JavaScript",
        description: "Make your pages interactive.",
        skills: ["DOM manipulation", "Events", "Fetching data from APIs"],
        resources: [{ label: "The Odin Project: JavaScript", url: "https://www.theodinproject.com" }],
        practiceProjectIdeas: ["A to-do list app", "A weather app using a public API"],
      },
      {
        title: "React",
        description: "Learn the library FutureDev projects are commonly built with.",
        skills: ["Components & props", "State", "Hooks"],
        resources: [{ label: "React documentation", url: "https://react.dev" }],
        practiceProjectIdeas: ["A recipe browser", "A campus club directory"],
      },
      {
        title: "Build a Full Project",
        description: "Put it all together into something real.",
        skills: ["Project structure", "Deployment"],
        resources: [{ label: "Next.js documentation", url: "https://nextjs.org/docs" }],
        practiceProjectIdeas: ["Ship a full project and share it in Discord"],
      },
    ],
  },
  {
    id: "mobile",
    title: "Mobile Development",
    description: "From your first screen to an app you can install on your phone.",
    stages: [
      {
        title: "Programming Fundamentals",
        description: "Learn how to think like a programmer before building UI.",
        skills: ["Variables & control flow", "Functions", "Working with JSON"],
        resources: [{ label: "freeCodeCamp: JavaScript Basics", url: "https://www.freecodecamp.org/learn" }],
        practiceProjectIdeas: ["A simple calculator script"],
      },
      {
        title: "Mobile UI Basics",
        description: "Learn how mobile interfaces are built.",
        skills: ["Layout & components", "Styling", "Touch interactions"],
        resources: [{ label: "React Native documentation", url: "https://reactnative.dev" }],
        practiceProjectIdeas: ["A single-screen habit tracker"],
      },
      {
        title: "State & Navigation",
        description: "Connect multiple screens into a real app.",
        skills: ["Component state", "Navigation between screens", "Forms"],
        resources: [{ label: "React Navigation documentation", url: "https://reactnavigation.org" }],
        practiceProjectIdeas: ["A multi-screen study-group matching app"],
      },
      {
        title: "Native APIs & Publishing",
        description: "Use device features and get ready to ship.",
        skills: ["Device APIs (camera, notifications)", "App configuration"],
        resources: [{ label: "Expo documentation", url: "https://docs.expo.dev" }],
        practiceProjectIdeas: ["Add push notifications to your app"],
      },
      {
        title: "Build a Full App",
        description: "Put it all together into an app you can install.",
        skills: ["Project structure", "Testing on a real device"],
        resources: [{ label: "Expo: Distributing your app", url: "https://docs.expo.dev/distribution/introduction/" }],
        practiceProjectIdeas: ["Ship a full app and share it in Discord"],
      },
    ],
  },
  {
    id: "game",
    title: "Game Development",
    description: "From your first prototype to a finished game jam entry.",
    stages: [
      {
        title: "Programming Fundamentals",
        description: "Learn how to think like a programmer before building gameplay.",
        skills: ["Variables & control flow", "Functions", "Basic C#"],
        resources: [{ label: "Unity Learn: Junior Programmer", url: "https://learn.unity.com" }],
        practiceProjectIdeas: ["A script that moves an object on screen"],
      },
      {
        title: "Game Engine Basics",
        description: "Get comfortable in a real game engine.",
        skills: ["Scenes & GameObjects", "Sprites & assets", "The game loop"],
        resources: [{ label: "Unity Learn", url: "https://learn.unity.com" }],
        practiceProjectIdeas: ["A character that can move and jump"],
      },
      {
        title: "Input, Camera & Physics",
        description: "Make your game respond to the player.",
        skills: ["Input System", "Camera & Transform", "Rigidbody & collisions"],
        resources: [{ label: "Unity Learn", url: "https://learn.unity.com" }],
        practiceProjectIdeas: ["A short platformer level"],
      },
      {
        title: "Game Design & Prototyping",
        description: "Turn a mechanic into something people actually enjoy playing.",
        skills: ["Prototyping", "Mechanics vs. dynamics", "Playtesting & iteration"],
        resources: [{ label: "Unity Learn", url: "https://learn.unity.com" }],
        practiceProjectIdeas: ["Playtest your prototype with a friend and iterate on the feedback"],
      },
      {
        title: "Build a Full Game",
        description: "Put it all together into a finished, playable game.",
        skills: ["Scope management", "Shipping"],
        resources: [{ label: "Unity Learn", url: "https://learn.unity.com" }],
        practiceProjectIdeas: ["Ship a game to itch.io and share it in Discord"],
      },
    ],
  },
  {
    id: "technical",
    title: "Technical Development",
    description: "From your first hash map to a set of interview stories you can tell confidently.",
    stages: [
      {
        title: "Programming Fundamentals for Interviews",
        description: "Get comfortable writing clean, correct functions under time pressure.",
        skills: ["Python or C++ basics", "Writing clean functions", "Basic debugging"],
        resources: [{ label: "LeetCode", url: "https://leetcode.com" }],
        practiceProjectIdeas: ["Solve a handful of easy problems to warm up"],
      },
      {
        title: "Arrays, Strings & Hashing",
        description: "Learn how to count, track, and check efficiently.",
        skills: ["Hash maps & frequency counting", "Sets", "String manipulation"],
        resources: [{ label: "LeetCode", url: "https://leetcode.com" }],
        practiceProjectIdeas: ["Build a small tool that counts word frequency in a text file"],
      },
      {
        title: "Two Pointers, Sliding Window & Binary Search",
        description: "Learn how to scan, compare, and narrow a search space efficiently.",
        skills: ["Two pointers", "Sliding window", "Binary search"],
        resources: [{ label: "LeetCode", url: "https://leetcode.com" }],
        practiceProjectIdeas: ["Track your solve times to see your speed improve"],
      },
      {
        title: "Linked Lists, Stacks, Queues & Trees",
        description: "Understand how nodes connect and how to explore structures systematically.",
        skills: ["Linked lists", "Stacks & queues", "Tree & graph traversal (DFS/BFS)"],
        resources: [{ label: "LeetCode", url: "https://leetcode.com" }],
        practiceProjectIdeas: ["Implement your own linked list and stack from scratch"],
      },
      {
        title: "Interview & Career Readiness",
        description: "Learn to talk about your work as clearly as you can code it.",
        skills: ["Resume writing", "Personal pitch & narrative", "Behavioral interviews (STAR method)"],
        resources: [],
        practiceProjectIdeas: ["Do a mock behavioral interview with a friend and swap feedback"],
      },
    ],
  },
];
