import type { LearningPath } from "@/types";

export const learningPaths: LearningPath[] = [
  {
    id: "web",
    title: "Web Development",
    description: "From your first line of HTML to a full-stack project you can show off.",
    stages: [
      {
        title: "Programming Fundamentals",
        description: "Learn how to think like a programmer before diving into the browser.",
        skills: ["Variables & control flow", "Functions", "Basic debugging"],
        resources: [{ label: "freeCodeCamp: JavaScript Basics", url: "https://www.freecodecamp.org/learn" }],
        workshops: [],
        practiceProjectIdeas: ["A number-guessing game in the browser console"],
      },
      {
        title: "HTML and CSS",
        description: "Structure and style your first real web pages.",
        skills: ["Semantic HTML", "CSS layout (flexbox/grid)", "Responsive design"],
        resources: [{ label: "MDN: Learn HTML and CSS", url: "https://developer.mozilla.org/en-US/docs/Learn" }],
        workshops: ["Intro to Web Dev Workshop"],
        practiceProjectIdeas: ["A personal landing page"],
      },
      {
        title: "JavaScript",
        description: "Make your pages interactive.",
        skills: ["DOM manipulation", "Events", "Fetching data from APIs"],
        resources: [{ label: "The Odin Project: JavaScript", url: "https://www.theodinproject.com" }],
        workshops: [],
        practiceProjectIdeas: ["A to-do list app", "A weather app using a public API"],
      },
      {
        title: "React",
        description: "Learn the library FutureDev projects are commonly built with.",
        skills: ["Components & props", "State", "Hooks"],
        resources: [{ label: "React documentation", url: "https://react.dev" }],
        workshops: ["Building with React"],
        practiceProjectIdeas: ["A recipe browser", "A campus club directory"],
      },
      {
        title: "Build a Full Project",
        description: "Put it all together into something real.",
        skills: ["Project structure", "Deployment"],
        resources: [{ label: "Next.js documentation", url: "https://nextjs.org/docs" }],
        workshops: [],
        practiceProjectIdeas: ["Ship a full project and share it in Discord"],
      },
    ],
  },
  {
    id: "mobile",
    title: "Mobile Development",
    description: "From your first screen to an app you can install on your phone.",
    stages: [
      {
        title: "Programming Fundamentals",
        description: "Learn how to think like a programmer before building UI.",
        skills: ["Variables & control flow", "Functions", "Working with JSON"],
        resources: [{ label: "freeCodeCamp: JavaScript Basics", url: "https://www.freecodecamp.org/learn" }],
        workshops: [],
        practiceProjectIdeas: ["A simple calculator script"],
      },
      {
        title: "Mobile UI Basics",
        description: "Learn how mobile interfaces are built.",
        skills: ["Layout & components", "Styling", "Touch interactions"],
        resources: [{ label: "React Native documentation", url: "https://reactnative.dev" }],
        workshops: ["Building Your First App"],
        practiceProjectIdeas: ["A single-screen habit tracker"],
      },
      {
        title: "State & Navigation",
        description: "Connect multiple screens into a real app.",
        skills: ["Component state", "Navigation between screens", "Forms"],
        resources: [{ label: "React Navigation documentation", url: "https://reactnavigation.org" }],
        workshops: [],
        practiceProjectIdeas: ["A multi-screen study-group matching app"],
      },
      {
        title: "Native APIs & Publishing",
        description: "Use device features and get ready to ship.",
        skills: ["Device APIs (camera, notifications)", "App configuration"],
        resources: [{ label: "Expo documentation", url: "https://docs.expo.dev" }],
        workshops: ["From Prototype to App Store"],
        practiceProjectIdeas: ["Add push notifications to your app"],
      },
      {
        title: "Build a Full App",
        description: "Put it all together into an app you can install.",
        skills: ["Project structure", "Testing on a real device"],
        resources: [{ label: "Expo: Distributing your app", url: "https://docs.expo.dev/distribution/introduction/" }],
        workshops: [],
        practiceProjectIdeas: ["Ship a full app and share it in Discord"],
      },
    ],
  },
  {
    id: "game",
    title: "Game Development",
    description: "From your first prototype to a finished game jam entry.",
    stages: [
      {
        title: "Programming Fundamentals",
        description: "Learn how to think like a programmer before building gameplay.",
        skills: ["Variables & control flow", "Functions", "Basic C#"],
        resources: [{ label: "Unity Learn: Junior Programmer", url: "https://learn.unity.com" }],
        workshops: [],
        practiceProjectIdeas: ["A script that moves an object on screen"],
      },
      {
        title: "Game Engine Basics",
        description: "Get comfortable in a real game engine.",
        skills: ["Scenes & GameObjects", "Sprites & assets", "The game loop"],
        resources: [{ label: "Unity Learn", url: "https://learn.unity.com" }],
        workshops: ["Intro to Game Dev with Unity"],
        practiceProjectIdeas: ["A character that can move and jump"],
      },
      {
        title: "Gameplay & Physics",
        description: "Make your game feel like a game.",
        skills: ["Collisions & physics", "Player input", "Level design basics"],
        resources: [{ label: "Godot documentation", url: "https://docs.godotengine.org" }],
        workshops: [],
        practiceProjectIdeas: ["A short platformer level"],
      },
      {
        title: "Polish & Publish",
        description: "Add the details that make a game feel finished.",
        skills: ["Sound & UI polish", "Playtesting"],
        resources: [{ label: "itch.io: Publishing a game", url: "https://itch.io/docs/creators/quick-start-guide" }],
        workshops: ["Game Jam Prep Night"],
        practiceProjectIdeas: ["Playtest your game with a friend and iterate"],
      },
      {
        title: "Build a Full Game",
        description: "Put it all together into a finished, playable game.",
        skills: ["Scope management", "Shipping"],
        resources: [{ label: "Unity Learn", url: "https://learn.unity.com" }],
        workshops: [],
        practiceProjectIdeas: ["Ship a game to itch.io and share it in Discord"],
      },
    ],
  },
  {
    id: "ai",
    title: "AI & Emerging Technology",
    description: "From your first Python script to a working AI-powered project.",
    stages: [
      {
        title: "Programming Fundamentals (Python)",
        description: "Learn the language most AI tooling is built around.",
        skills: ["Python syntax", "Functions", "Working with libraries"],
        resources: [{ label: "Python's official tutorial", url: "https://docs.python.org/3/tutorial/" }],
        workshops: ["Intro to Python for AI"],
        practiceProjectIdeas: ["A script that analyzes a CSV file"],
      },
      {
        title: "Working with Data",
        description: "Learn to clean and explore real data.",
        skills: ["Data structures", "pandas basics", "Data visualization"],
        resources: [{ label: "Kaggle: Pandas course", url: "https://www.kaggle.com/learn/pandas" }],
        workshops: [],
        practiceProjectIdeas: ["Explore a public dataset and chart something interesting"],
      },
      {
        title: "Machine Learning Basics",
        description: "Understand how models learn from data.",
        skills: ["Supervised learning basics", "Training & evaluation"],
        resources: [{ label: "Google's Machine Learning Crash Course", url: "https://developers.google.com/machine-learning/crash-course" }],
        workshops: [],
        practiceProjectIdeas: ["Train a simple image classifier"],
      },
      {
        title: "Using AI/LLM APIs",
        description: "Build with today's AI models without training your own.",
        skills: ["API requests", "Prompting", "Handling responses"],
        resources: [{ label: "OpenAI API documentation", url: "https://platform.openai.com/docs" }],
        workshops: ["Building with LLM APIs"],
        practiceProjectIdeas: ["A chatbot for a topic you know well"],
      },
      {
        title: "Build a Full AI Project",
        description: "Put it all together into a real, working AI project.",
        skills: ["Project structure", "Deployment basics"],
        resources: [{ label: "FastAPI documentation", url: "https://fastapi.tiangolo.com" }],
        workshops: [],
        practiceProjectIdeas: ["Ship a full AI project and share it in Discord"],
      },
    ],
  },
];
