import type { TeamMember } from "@/types";

// 2026-2027 Executive Board.
export const team: TeamMember[] = [
  {
    id: "chris-ridad",
    name: "Chris Ridad",
    role: "President",
    year: "Senior",
    program: "CS + Psych",
    hometown: "North Texas",
    funFact: "I'm Colombian, Filipino, Indian, and Fijian!",
    photo: "/team/chris-ridad.png",
    photoPosition: "0% 0%",
  },
  {
    id: "jack-press",
    name: "Jack Press",
    role: "Treasurer",
    year: "Senior",
    program: "CS McCormick",
    hometown: "Chicago",
    funFact: "I have spent about $500 on rubber ducks!",
    photo: "/team/jack-press.png",
    photoPosition: "0% 25%",
  },
  {
    id: "melanie-cuenca",
    name: "Melanie Cuenca",
    role: "Director of Community Engagement",
    year: "Senior",
    program: "CS McCormick",
    hometown: "Chicago",
    funFact: "I moved to the US when I was 8.",
    photo: "/team/melanie-cuenca.png",
    photoPosition: "50% 35%",
  },
  {
    id: "mariana-ma",
    name: "Mariana Ma",
    role: "Co-Director of Education",
    year: "Senior",
    program: "CS",
    hometown: "Franklin, Massachusetts",
    funFact: "I have 2 cats.",
    photo: "/team/mariana-ma.png",
    photoPosition: "50% 25%",
  },
  {
    id: "joanna-echeverri-porras",
    name: "Joanna Echeverri Porras",
    role: "Co-Director of Education",
    year: "Senior",
    program: "CS McCormick",
    hometown: "South Florida",
    funFact: "I've been a part of 8 musicals!",
    photo: "/team/joanna-porras.png",
    photoZoom: 1.25,
  },
  {
    id: "christina-feng",
    name: "Christina Feng",
    role: "Director of Operations",
    year: "Senior",
    program: "CS + Cog Sci",
    hometown: "NY",
    funFact: "I have 300+ photos of the sky on my phone.",
    photo: "/team/christina-feng.png",
    photoZoom: 1.5,
  },
];
